# Name of project
name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Profile type used by dbt
profile: 'default'

# Configurations that indicate which type of files dbt needs to look for.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
      relation: true
      columns: true
  dbt_project:
    staging:
      +materialized: view
      ae_assessment_lguiral:
        schema: stg_ae_assessment_lguiral
    intermediate:
      +materialized: table
    mart:
      schema: mart
